development:
    twilio:
      from: '+12692056408'
      sid: 'ACcbedf28d420b79c50d8acba6e98bd951'
      token: 'd09d6a6fbc0999ef7e6b56d75a890c79'
    robokassa:
      login: "testlogin"
      secret: "secret"
test:
    twilio:
      from: '+12692056408'
      sid: 'ACcbedf28d420b79c50d8acba6e98bd951'
      token: 'd09d6a6fbc0999ef7e6b56d75a890c79'
    robokassa:
      login: "testlogin"
      secret: "secret"
production:
    twilio:
      from: '+12692056408'
      sid: 'ACcbedf28d420b79c50d8acba6e98bd951'
      token: 'd09d6a6fbc0999ef7e6b56d75a890c79'
